import { NodeRegion } from "../node-region";

export const nodeRegionsMock: NodeRegion[] = [
	{whoisRegion: 'Sydney', whoisCountry: 'Australia'},
	{whoisRegion: 'Vienna', whoisCountry: 'Austria'},
	{whoisRegion: 'Minsk', whoisCountry: 'Belarus'},
	{whoisRegion: 'Zaventem', whoisCountry: 'Belgium'},
	{whoisRegion: 'San Paulo', whoisCountry: 'Brazil'},
	{whoisRegion: 'Sofia', whoisCountry: 'Bulgaria'},
	{whoisRegion: 'Beauharnois', whoisCountry: 'Canada'},
	{whoisRegion: 'Montreal', whoisCountry: 'Canada'},
	{whoisRegion: 'Toronto', whoisCountry: 'Canada'},
	{whoisRegion: 'Hong Kong', whoisCountry: 'China'},
	{whoisRegion: 'Prague', whoisCountry: 'Czech'},
	{whoisRegion: 'Helsinki', whoisCountry: 'Finland'},
	{whoisRegion: 'Gravelines', whoisCountry: 'France'},
	{whoisRegion: 'Paris', whoisCountry: 'France'},
	{whoisRegion: 'Roubaix', whoisCountry: 'France'},
	{whoisRegion: 'Strasbourg', whoisCountry: 'France'},
	{whoisRegion: 'Dusseldorf', whoisCountry: 'Germany'},
	{whoisRegion: 'Falkenstein', whoisCountry: 'Germany'},
	{whoisRegion: 'Frankfurt', whoisCountry: 'Germany'},
	{whoisRegion: 'Nuremberg', whoisCountry: 'Germany'},
	{whoisRegion: 'Saarbrucken', whoisCountry: 'Germany'},
	{whoisRegion: 'Bangalore', whoisCountry: 'India'},
	{whoisRegion: 'Mumbai', whoisCountry: 'India'},
	{whoisRegion: 'Dublin', whoisCountry: 'Ireland'},
	{whoisRegion: 'Milan', whoisCountry: 'Italy'},
	{whoisRegion: 'Tokyo', whoisCountry: 'Japan'},
	{whoisRegion: 'Riga', whoisCountry: 'Latvia'},
	{whoisRegion: 'Vilnius', whoisCountry: 'Lithuania'},
	{whoisRegion: 'Amsterdam', whoisCountry: 'Netherlands'},
	{whoisRegion: 'Rotterdam', whoisCountry: 'Netherlands'},
	{whoisRegion: 'Oslo', whoisCountry: 'Norway'},
	{whoisRegion: 'Gdansk', whoisCountry: 'Poland'},
	{whoisRegion: 'Wroclaw', whoisCountry: 'Poland'},
	{whoisRegion: 'Lisbon', whoisCountry: 'Portugal'},
	{whoisRegion: 'Johannesburg', whoisCountry: 'Republic of South Africa'},
	{whoisRegion: 'Chelyabinsk', whoisCountry: 'Russia'},
	{whoisRegion: 'Khabarovsk', whoisCountry: 'Russia'},
	{whoisRegion: 'Krasnoyarsk', whoisCountry: 'Russia'},
	{whoisRegion: 'Moscow', whoisCountry: 'Russia'},
	{whoisRegion: 'Novosibirsk', whoisCountry: 'Russia'},
	{whoisRegion: 'Saint Petersburg', whoisCountry: 'Russia'},
	{whoisRegion: 'Tomsk', whoisCountry: 'Russia'},
	{whoisRegion: 'Yekaterinburg', whoisCountry: 'Russia'},
	{whoisRegion: 'Singapore', whoisCountry: 'Singapore'},
	{whoisRegion: 'Seoul', whoisCountry: 'South Korea'},
	{whoisRegion: 'Madrid', whoisCountry: 'Spain'},
	{whoisRegion: 'Valencia', whoisCountry: 'Spain'},
	{whoisRegion: 'Stockholm', whoisCountry: 'Sweden'},
	{whoisRegion: 'Zurich', whoisCountry: 'Switzerland'},
	{whoisRegion: 'Istanbul', whoisCountry: 'Turkey'},
	{whoisRegion: 'Kharkiv', whoisCountry: 'Ukraine'},
	{whoisRegion: 'Kiev', whoisCountry: 'Ukraine'},
	{whoisRegion: 'London', whoisCountry: 'United Kingdom'},
	{whoisRegion: 'Chicago', whoisCountry: 'USA'},
	{whoisRegion: 'Dallas', whoisCountry: 'USA'},
	{whoisRegion: 'Kansas City', whoisCountry: 'USA'},
	{whoisRegion: 'Los Angeles', whoisCountry: 'USA'},
	{whoisRegion: 'New York', whoisCountry: 'USA'},
	{whoisRegion: 'Portland', whoisCountry: 'USA'},
	{whoisRegion: 'San Francisco', whoisCountry: 'USA'},
	{whoisRegion: 'Washington', whoisCountry: 'USA'},
];